import { User, Prompt, Post, PromptCategory, PromptLevel, PromptLanguage } from '../types';

export const mockUsers: User[] = [
  { 
    id: 'user-1', 
    username: 'علي الأحمد', 
    avatar_url: 'https://picsum.photos/seed/user1/100/100', 
    is_premium: true, 
    created_at: '2024-01-15T10:00:00Z',
    bio: 'مطور واجهات أمامية وشغوف بالذكاء الاصطناعي. أشارك هنا أفضل الأوامر التي أكتشفها.',
    website: 'https://ali-ahmad.dev',
    social: {
      twitter: 'ali_ahmad_dev',
      github: 'ali-ahmad',
      linkedin: 'ali-ahmad-dev'
    }
  },
  { 
    id: 'user-2', 
    username: 'فاطمة الزهراء', 
    avatar_url: 'https://picsum.photos/seed/user2/100/100',
    // FIX: Added missing 'created_at' property to satisfy the User interface.
    created_at: '2024-03-10T14:30:00Z',
    bio: 'مصممة جرافيك وفنانة رقمية. أستخدم الذكاء الاصطناعي لإنشاء أعمال فنية مذهلة.',
    website: 'https://fatima-art.com',
    social: {
      twitter: 'fatima_art',
    }
  },
];

export const mockPrompts: Prompt[] = [
  // === TEXT Prompts (10) ===
  {
    id: 'prompt-1',
    slug: 'تلخيص-مقال-علمي-معقد',
    title: 'تلخيص مقال علمي معقد',
    prompt_text: 'لخص المقال العلمي التالي في 300 كلمة، مع التركيز على المنهجية والنتائج الرئيسية. يجب أن يكون التلخيص واضحًا لغير المتخصصين. [الصق نص المقال هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تلخيص', 'أكاديمي', 'علمي'],
    created_at: '2024-07-25T10:00:00Z',
    likes: 150,
    views: 600,
    verified: true,
  },
  {
    id: 'prompt-2',
    slug: 'كتابة-بريد-إلكتروني-احترافي-لطلب-شراكة',
    title: 'كتابة بريد إلكتروني احترافي لطلب شراكة',
    prompt_text: 'اكتب بريدًا إلكترونيًا إلى مدير التسويق في شركة [اسم الشركة] تقترح فيه شراكة استراتيجية بين شركتنا ومنصتهم. أبرز الفوائد المتبادلة وقدم دعوة واضحة لاجتماع.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['بريد إلكتروني', 'أعمال', 'شراكة'],
    created_at: '2024-07-25T09:00:00Z',
    likes: 210,
    views: 850,
  },
  {
    id: 'prompt-3',
    title: 'إنشاء شخصية لروبوت محادثة ودود',
    prompt_text: 'حدد شخصية لروبوت محادثة (chatbot) يعمل كمساعد افتراضي في متجر لبيع الكتب. يجب أن تكون الشخصية ودودة، مثقفة، وقادرة على تقديم توصيات كتب مخصصة بأسلوب جذاب.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['شخصية AI', 'روبوت محادثة', 'كتابة إبداعية'],
    created_at: '2024-07-24T18:00:00Z',
    likes: 95,
    views: 430,
  },
  {
    id: 'prompt-4',
    title: 'ترجمة مصطلحات تقنية من الإنجليزية للعربية',
    prompt_text: 'ترجم قائمة المصطلحات التقنية التالية من الإنجليزية إلى العربية، مع تقديم شرح مبسط لكل مصطلح. القائمة: [API, Machine Learning, Blockchain, Cloud Computing, SaaS]',
    category: PromptCategory.TEXT,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['ترجمة', 'تقنية', 'مصطلحات'],
    created_at: '2024-07-24T15:00:00Z',
    likes: 180,
    views: 720,
    verified: true,
  },
  {
    id: 'prompt-5',
    title: 'تحليل مشاعر (Sentiment Analysis) لآراء العملاء',
    prompt_text: 'حلل المشاعر في مراجعات العملاء التالية وصنفها إلى (إيجابي، سلبي، محايد). استخرج الأسباب الرئيسية وراء كل تصنيف. [الصق مراجعات العملاء هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تحليل بيانات', 'مشاعر', 'NPL'],
    created_at: '2024-07-23T11:00:00Z',
    likes: 250,
    views: 1100,
  },
  {
    id: 'prompt-6',
    title: 'صياغة أسئلة مقابلة لوظيفة مدير مشروع',
    prompt_text: 'صمم قائمة من 10 أسئلة سلوكية وتقنية لمقابلة مرشح لوظيفة مدير مشروع في شركة برمجيات. يجب أن تغطي الأسئلة مجالات مثل إدارة الفرق، ومنهجيات Agile، وإدارة المخاطر.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['موارد بشرية', 'مقابلة', 'إدارة مشاريع'],
    created_at: '2024-07-23T09:30:00Z',
    likes: 120,
    views: 550,
  },
  {
    id: 'prompt-7',
    title: 'إعادة صياغة نص لجعله أكثر إيجازًا',
    prompt_text: 'أعد صياغة الفقرة التالية لجعلها أكثر إيجازًا وقوة، مع الحفاظ على المعنى الأساسي. [الصق الفقرة هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تحرير', 'كتابة', 'إيجاز'],
    created_at: '2024-07-22T14:00:00Z',
    likes: 88,
    views: 400,
  },
  {
    id: 'prompt-8',
    title: 'استخراج الكيانات المسماة (NER) من خبر صحفي',
    prompt_text: 'استخرج جميع الكيانات المسماة (أشخاص، منظمات، مواقع، تواريخ) من الخبر الصحفي التالي. [الصق الخبر هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['NER', 'معالجة اللغات', 'استخراج معلومات'],
    created_at: '2024-07-22T10:00:00Z',
    likes: 165,
    views: 680,
    verified: true,
  },
  {
    id: 'prompt-9',
    title: 'إنشاء حوار بين شخصيتين تاريخيتين',
    prompt_text: 'اكتب حوارًا خياليًا بين ابن خلدون وليوناردو دافنشي يناقشان فيه العلاقة بين العلم والفن.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['حوار', 'تاريخ', 'كتابة إبداعية'],
    created_at: '2024-07-21T16:00:00Z',
    likes: 310,
    views: 1200,
  },
  {
    id: 'prompt-10',
    title: 'توليد أفكار لعناوين مقالات حول الذكاء الاصطناعي',
    prompt_text: 'اقترح 10 عناوين جذابة لمقالات مدونة تستهدف المبتدئين في مجال الذكاء الاصطناعي.',
    category: PromptCategory.TEXT,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['توليد أفكار', 'تسويق محتوى', 'عناوين'],
    created_at: '2024-07-21T12:00:00Z',
    likes: 190,
    views: 800,
  },

  // === IMAGE Prompts (10) ===
  {
    id: 'prompt-11',
    title: 'صورة فوتوغرافية لقهوة عربية تقليدية',
    prompt_text: 'صورة فوتوغرافية واقعية للغاية لفنجان قهوة عربية بجانب تمر، على سجادة بدوية، مع إضاءة دافئة وناعمة تأتي من نافذة.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تصوير', 'واقعي', 'قهوة', 'تقليدي'],
    created_at: '2024-07-25T15:30:00Z',
    likes: 256,
    views: 890,
    verified: true,
  },
  {
    id: 'prompt-12',
    title: 'مدينة مستقبلية بأسلوب السايبربانك العربي',
    prompt_text: 'فن رقمي مفصل لمدينة الرياض في عام 2088، بأسلوب السايبربانك، أسواق ليلية مضاءة بالنيون، مركبات طائرة، أبراج شاهقة ممزوجة بالعمارة النجدية، cinematic lighting, ultra detailed, 8k.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[0],
    tags: ['سايبربانك', 'فن رقمي', 'خيال علمي', 'مدينة'],
    created_at: '2024-07-25T11:00:00Z',
    likes: 420,
    views: 1500,
  },
  {
    id: 'prompt-13',
    title: 'شعار بسيط لعلامة تجارية للتمور الفاخرة',
    prompt_text: 'شعار بسيط (minimalist logo) لعلامة تجارية اسمها "نخيل"، تبيع التمور الفاخرة. استخدم خطًا عربيًا أنيقًا مع أيقونة نخلة مبسطة. vector, flat design, luxury.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['شعار', 'تصميم جرافيك', 'بسيط'],
    created_at: '2024-07-24T14:00:00Z',
    likes: 180,
    views: 750,
  },
  // FIX: Completed the prompt object to satisfy the Prompt interface.
  {
    id: 'prompt-14',
    title: 'رسمة قط لطيف بأسلوب الرسوم المتحركة',
    slug: 'رسمة-قط-لطيف-كرتون',
    prompt_text: 'رسمة كرتونية بسيطة ولطيفة لقط برتقالي صغير يجلس في صندوق من الورق المقوى، بأسلوب فني بسيط، خلفية بيضاء، digital art.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['قط', 'رسوم متحركة', 'لطيف', 'فن رقمي'],
    created_at: '2024-07-23T18:00:00Z',
    likes: 220,
    views: 950
  },
];

// FIX: Added mockPosts data to be used throughout the application.
export const mockPosts: Post[] = [
  {
    id: 'post-1',
    title: '5 نصائح لكتابة أوامر احترافية لـ Midjourney',
    slug: '5-نصائح-لكتابة-أوامر-احترافية-لـ-midjourney',
    content_html: `<p>هل ترغب في الحصول على أفضل النتائج من Midjourney؟ الأمر كله يبدأ من جودة الأمر (Prompt) الذي تكتبه. في هذا المقال، سنستعرض 5 نصائح أساسية لتحويل أفكارك إلى صور مذهلة.</p><h3>1. كن محددًا قدر الإمكان</h3><p>بدلاً من كتابة "سيارة رياضية"، جرب "سيارة رياضية حمراء من نوع فيراري موديل 1985، تسير بسرعة على طريق ساحلي عند غروب الشمس". كلما زادت التفاصيل، كانت النتيجة أقرب لتصورك.</p><h3>2. استخدم الكلمات المفتاحية للأسلوب</h3><p>أضف كلمات مثل "cinematic lighting", "ultra realistic", "8k", "fantasy art", "vaporwave" لتوجيه الذكاء الاصطناعي نحو الأسلوب الفني الذي تريده.</p><h3>3. جرب أوزان الكلمات</h3><p>يمكنك استخدام <code>::</code> لتحديد أهمية كلمة معينة. مثال: <code>cat::2 dog::1</code> سيعطي أهمية أكبر للقط في الصورة.</p>`,
    author: mockUsers[0],
    published_at: '2024-07-20T09:00:00Z',
    featured_image: 'https://picsum.photos/seed/post1/600/400',
    is_trending: true,
    tags: ['Midjourney', 'توليد صور', 'نصائح', 'ذكاء اصطناعي'],
    views: 12500,
    comments_count: 15,
    reactions: { heart: 250, insightful: 120, funny: 30, fire: 80 },
  },
  {
    id: 'post-2',
    title: 'كيف تستخدم ChatGPT لتعلم لغة جديدة؟',
    slug: 'كيف-تستخدم-chatgpt-لتعلم-لغة-جديدة',
    content_html: `<p>يعتبر ChatGPT أداة قوية ليس فقط للإجابة على الأسئلة، بل يمكن أن يكون شريكك المثالي في رحلة تعلم لغة جديدة. إليك بعض الأوامر التي يمكنك استخدامها:</p><ul><li>"اشرح لي قاعدة المضارع البسيط في اللغة الإنجليزية مع أمثلة."</li><li>"صحح لي هذه الجملة: I goed to the store."</li><li>"دعنا نقم بمحادثة بسيطة باللغة الإسبانية حول الطقس."</li></ul><p>الاستمرارية هي المفتاح. حاول تخصيص 15 دقيقة يوميًا للتحدث مع ChatGPT بلغتك الهدف.</p>`,
    author: mockUsers[1],
    published_at: '2024-07-18T14:00:00Z',
    featured_image: 'https://picsum.photos/seed/post2/600/400',
    is_trending: false,
    tags: ['ChatGPT', 'تعلم لغات', 'إنتاجية'],
    views: 8900,
    comments_count: 8,
    reactions: { heart: 180, insightful: 210, funny: 10, fire: 45 },
  },
    {
    id: 'post-3',
    title: 'مقدمة إلى هندسة الأوامر (Prompt Engineering)',
    slug: 'مقدمة-إلى-هندسة-الأوامر',
    content_html: `<p>هندسة الأوامر هي فن وعلم صياغة المدخلات (الأوامر) لنماذج الذكاء الاصطناعي للحصول على أفضل المخرجات الممكنة. إنها مهارة أساسية لأي شخص يريد الاستفادة القصوى من أدوات الذكاء الاصطناعي التوليدي.</p><p>لا يتعلق الأمر فقط بما تطلبه، ولكن كيف تطلبه. بنية الأمر، السياق الذي تقدمه، وحتى الكلمات التي تختارها يمكن أن تحدث فرقًا كبيرًا في جودة الاستجابة.</p>`,
    author: mockUsers[0],
    published_at: '2024-07-15T11:20:00Z',
    featured_image: 'https://picsum.photos/seed/post3/600/400',
    is_trending: false,
    tags: ['هندسة الأوامر', 'مبتدئين', 'أساسيات'],
    views: 15320,
    comments_count: 22,
    reactions: { heart: 310, insightful: 450, funny: 5, fire: 110 },
  },
];

// FIX: Added functions to mutate mock data arrays for form submissions.
export const addPrompt = (prompt: Prompt) => {
  mockPrompts.unshift(prompt);
};

export const addPost = (post: Post) => {
  mockPosts.unshift(post);
};
