import { User, Prompt, Post, PromptCategory, PromptLevel, PromptLanguage } from '../types';

export const mockUsers: User[] = [
  { 
    id: 'user-1', 
    username: 'علي الأحمد', 
    avatar_url: 'https://picsum.photos/seed/user1/100/100', 
    is_premium: true, 
    created_at: '2024-01-15T10:00:00Z',
    bio: 'مطور واجهات أمامية وشغوف بالذكاء الاصطناعي. أشارك هنا أفضل الأوامر التي أكتشفها.',
    website: 'https://ali-ahmad.dev',
    social: {
      twitter: 'ali_ahmad_dev',
      github: 'ali-ahmad',
      linkedin: 'ali-ahmad-dev'
    }
  },
  { 
    id: 'user-2', 
    username: 'فاطمة الزهراء', 
    avatar_url: 'https://picsum.photos/seed/user2/100/100',
    // FIX: Added missing 'created_at' property to satisfy the User interface.
    created_at: '2024-03-10T14:30:00Z',
    bio: 'مصممة جرافيك وفنانة رقمية. أستخدم الذكاء الاصطناعي لإنشاء أعمال فنية مذهلة.',
    website: 'https://fatima-art.com',
    social: {
      twitter: 'fatima_art',
    }
  },
];

export const mockPrompts: Prompt[] = [
  // === TEXT Prompts (10) ===
  {
    id: 'prompt-1',
    slug: 'تلخيص-مقال-علمي-معقد',
    title: 'تلخيص مقال علمي معقد',
    prompt_text: 'لخص المقال العلمي التالي في 300 كلمة، مع التركيز على المنهجية والنتائج الرئيسية. يجب أن يكون التلخيص واضحًا لغير المتخصصين. [الصق نص المقال هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تلخيص', 'أكاديمي', 'علمي'],
    created_at: '2024-07-25T10:00:00Z',
    likes: 150,
    views: 600,
    verified: true,
  },
  {
    id: 'prompt-2',
    slug: 'كتابة-بريد-إلكتروني-احترافي-لطلب-شراكة',
    title: 'كتابة بريد إلكتروني احترافي لطلب شراكة',
    prompt_text: 'اكتب بريدًا إلكترونيًا إلى مدير التسويق في شركة [اسم الشركة] تقترح فيه شراكة استراتيجية بين شركتنا ومنصتهم. أبرز الفوائد المتبادلة وقدم دعوة واضحة لاجتماع.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['بريد إلكتروني', 'أعمال', 'شراكة'],
    created_at: '2024-07-25T09:00:00Z',
    likes: 210,
    views: 850,
  },
  {
    id: 'prompt-3',
    title: 'إنشاء شخصية لروبوت محادثة ودود',
    prompt_text: 'حدد شخصية لروبوت محادثة (chatbot) يعمل كمساعد افتراضي في متجر لبيع الكتب. يجب أن تكون الشخصية ودودة، مثقفة، وقادرة على تقديم توصيات كتب مخصصة بأسلوب جذاب.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['شخصية AI', 'روبوت محادثة', 'كتابة إبداعية'],
    created_at: '2024-07-24T18:00:00Z',
    likes: 95,
    views: 430,
  },
  {
    id: 'prompt-4',
    title: 'ترجمة مصطلحات تقنية من الإنجليزية للعربية',
    prompt_text: 'ترجم قائمة المصطلحات التقنية التالية من الإنجليزية إلى العربية، مع تقديم شرح مبسط لكل مصطلح. القائمة: [API, Machine Learning, Blockchain, Cloud Computing, SaaS]',
    category: PromptCategory.TEXT,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['ترجمة', 'تقنية', 'مصطلحات'],
    created_at: '2024-07-24T15:00:00Z',
    likes: 180,
    views: 720,
    verified: true,
  },
  {
    id: 'prompt-5',
    title: 'تحليل مشاعر (Sentiment Analysis) لآراء العملاء',
    prompt_text: 'حلل المشاعر في مراجعات العملاء التالية وصنفها إلى (إيجابي، سلبي، محايد). استخرج الأسباب الرئيسية وراء كل تصنيف. [الصق مراجعات العملاء هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تحليل بيانات', 'مشاعر', 'NPL'],
    created_at: '2024-07-23T11:00:00Z',
    likes: 250,
    views: 1100,
  },
  {
    id: 'prompt-6',
    title: 'صياغة أسئلة مقابلة لوظيفة مدير مشروع',
    prompt_text: 'صمم قائمة من 10 أسئلة سلوكية وتقنية لمقابلة مرشح لوظيفة مدير مشروع في شركة برمجيات. يجب أن تغطي الأسئلة مجالات مثل إدارة الفرق، ومنهجيات Agile، وإدارة المخاطر.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['موارد بشرية', 'مقابلة', 'إدارة مشاريع'],
    created_at: '2024-07-23T09:30:00Z',
    likes: 120,
    views: 550,
  },
  {
    id: 'prompt-7',
    title: 'إعادة صياغة نص لجعله أكثر إيجازًا',
    prompt_text: 'أعد صياغة الفقرة التالية لجعلها أكثر إيجازًا وقوة، مع الحفاظ على المعنى الأساسي. [الصق الفقرة هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تحرير', 'كتابة', 'إيجاز'],
    created_at: '2024-07-22T14:00:00Z',
    likes: 88,
    views: 400,
  },
  {
    id: 'prompt-8',
    title: 'استخراج الكيانات المسماة (NER) من خبر صحفي',
    prompt_text: 'استخرج جميع الكيانات المسماة (أشخاص، منظمات، مواقع، تواريخ) من الخبر الصحفي التالي. [الصق الخبر هنا]',
    category: PromptCategory.TEXT,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['NER', 'معالجة اللغات', 'استخراج معلومات'],
    created_at: '2024-07-22T10:00:00Z',
    likes: 165,
    views: 680,
    verified: true,
  },
  {
    id: 'prompt-9',
    title: 'إنشاء حوار بين شخصيتين تاريخيتين',
    prompt_text: 'اكتب حوارًا خياليًا بين ابن خلدون وليوناردو دافنشي يناقشان فيه العلاقة بين العلم والفن.',
    category: PromptCategory.TEXT,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['حوار', 'تاريخ', 'كتابة إبداعية'],
    created_at: '2024-07-21T16:00:00Z',
    likes: 310,
    views: 1200,
  },
  {
    id: 'prompt-10',
    title: 'توليد أفكار لعناوين مقالات حول الذكاء الاصطناعي',
    prompt_text: 'اقترح 10 عناوين جذابة لمقالات مدونة تستهدف المبتدئين في مجال الذكاء الاصطناعي.',
    category: PromptCategory.TEXT,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['توليد أفكار', 'تسويق محتوى', 'عناوين'],
    created_at: '2024-07-21T12:00:00Z',
    likes: 190,
    views: 800,
  },

  // === IMAGE Prompts (10) ===
  {
    id: 'prompt-11',
    title: 'صورة فوتوغرافية لقهوة عربية تقليدية',
    prompt_text: 'صورة فوتوغرافية واقعية للغاية لفنجان قهوة عربية بجانب تمر، على سجادة بدوية، مع إضاءة دافئة وناعمة تأتي من نافذة.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تصوير', 'واقعي', 'قهوة', 'تقليدي'],
    created_at: '2024-07-25T15:30:00Z',
    likes: 256,
    views: 890,
    verified: true,
  },
  {
    id: 'prompt-12',
    title: 'مدينة مستقبلية بأسلوب السايبربانك العربي',
    prompt_text: 'فن رقمي مفصل لمدينة الرياض في عام 2088، بأسلوب السايبربانك، أسواق ليلية مضاءة بالنيون، مركبات طائرة، أبراج شاهقة ممزوجة بالعمارة النجدية، cinematic lighting, ultra detailed, 8k.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[0],
    tags: ['سايبربانك', 'فن رقمي', 'خيال علمي', 'مدينة'],
    created_at: '2024-07-25T11:00:00Z',
    likes: 420,
    views: 1500,
  },
  {
    id: 'prompt-13',
    title: 'شعار بسيط لعلامة تجارية للتمور الفاخرة',
    prompt_text: 'شعار بسيط (minimalist logo) لعلامة تجارية اسمها "نخيل"، تبيع التمور الفاخرة. استخدم خطًا عربيًا أنيقًا مع أيقونة نخلة مبسطة. vector, flat design, luxury.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['شعار', 'تصميم جرافيك', 'بسيط'],
    created_at: '2024-07-24T14:00:00Z',
    likes: 180,
    views: 750,
  },
  {
    id: 'prompt-14',
    title: 'رسمة قط يرتدي زي رائد فضاء',
    prompt_text: 'رسمة كرتونية لطيفة لقط من فصيلة الشيرازي يرتدي خوذة رائد فضاء وينظر من نافذة مركبة فضائية إلى كوكب الأرض.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['كرتون', 'قط', 'فضاء', 'لطيف'],
    created_at: '2024-07-24T10:00:00Z',
    likes: 350,
    views: 1300,
    verified: true,
  },
  {
    id: 'prompt-15',
    title: 'تصميم داخلي لمجلس عربي عصري',
    prompt_text: 'تصميم داخلي (interior design) لمجلس عربي عصري، يدمج بين الأثاث المودرن والزخارف الإسلامية، مع إضاءة طبيعية واسعة وألوان ترابية. 3d render, photorealistic, architectural digest.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['تصميم داخلي', 'عصري', 'مجلس'],
    created_at: '2024-07-23T16:00:00Z',
    likes: 280,
    views: 950,
  },
  {
    id: 'prompt-16',
    title: 'غلاف كتاب خيال علمي',
    prompt_text: 'تصميم غلاف كتاب لرواية خيال علمي بعنوان "بوابة الرمال". يجب أن يظهر الغلاف بوابة حجرية قديمة في وسط صحراء شاسعة، ومن خلالها يمكن رؤية نجوم ومجرات.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['غلاف كتاب', 'فن', 'خيال علمي'],
    created_at: '2024-07-23T12:00:00Z',
    likes: 205,
    views: 820,
  },
  {
    id: 'prompt-17',
    title: 'نمط (Pattern) زخرفي إسلامي غير ملحوم',
    prompt_text: 'نمط زخرفي إسلامي هندسي غير ملحوم (seamless pattern)، بألوان الأزرق الداكن والذهبي. مناسب للاستخدام كخلفية. vector, intricate details.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['نمط', 'زخرفة إسلامية', 'تصميم'],
    created_at: '2024-07-22T17:00:00Z',
    likes: 310,
    views: 1150,
    verified: true,
  },
  {
    id: 'prompt-18',
    title: 'طبق كبسة شهي، تصوير طعام',
    prompt_text: 'صورة طعام احترافية (food photography) لطبق كبسة دجاج كبير مزين بالمكسرات والبصل المقلي، لقطة من زاوية علوية (top-down shot), macro details, delicious.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تصوير طعام', 'كبسة', 'واقعي'],
    created_at: '2024-07-22T13:00:00Z',
    likes: 290,
    views: 1000,
  },
  {
    id: 'prompt-19',
    title: 'شخصية فارس عربي من العصور الوسطى',
    prompt_text: 'تصميم شخصية (character design) لفارس عربي شجاع من العصور الوسطى، يرتدي درعًا معدنيًا مزخرفًا ويحمل سيفًا منحنيًا، يقف أمام قلعة في الصحراء. fantasy art, detailed armor, concept art.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['تصميم شخصيات', 'فن خيالي', 'فارس'],
    created_at: '2024-07-21T19:00:00Z',
    likes: 380,
    views: 1400,
  },
  {
    id: 'prompt-20',
    title: 'أيقونات لتطبيق طقس',
    prompt_text: 'مجموعة من 6 أيقونات لتطبيق طقس (sunny, cloudy, rainy, stormy, snowy, night). تصميم مسطح (flat design), أسلوب بسيط وملون. UI icons, vector.',
    category: PromptCategory.IMAGE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[0],
    tags: ['أيقونات', 'UI/UX', 'تصميم مسطح'],
    created_at: '2024-07-21T14:00:00Z',
    likes: 220,
    views: 900,
    verified: true,
  },

  // === VIDEO Prompts (10) ===
  {
    id: 'prompt-21',
    title: 'فيديو قصير عن الصحراء العربية',
    prompt_text: 'فيديو سينمائي قصير يظهر جمال الصحراء العربية عند شروق الشمس، لقطات واسعة للكثبان الرملية الذهبية، مع جمل يسير ببطء في الأفق، وموسيقى تصويرية هادئة وملهمة.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[0],
    tags: ['سينمائي', 'طبيعة', 'صحراء'],
    created_at: '2024-07-25T08:45:00Z',
    likes: 418,
    views: 1200,
    verified: true,
  },
  {
    id: 'prompt-22',
    title: 'إعلان قصير لمنتج قهوة سريعة التحضير',
    prompt_text: 'فيديو إعلاني مدته 15 ثانية لمنتج قهوة سريعة التحضير، يظهر شخصًا يستيقظ بنشاط بعد شرب القهوة. لقطات سريعة وحيوية، مع موسيقى مبهجة.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['إعلان', 'قهوة', 'تسويق'],
    created_at: '2024-07-25T07:00:00Z',
    likes: 180,
    views: 700,
  },
  {
    id: 'prompt-23',
    title: 'فيديو طهي سريع لوصفة حمص',
    prompt_text: 'فيديو سريع (timelapse) مدته دقيقة واحدة يوضح خطوات تحضير الحمص بالطحينة من البداية إلى النهاية. تصوير من الأعلى (top-down view)، مع ظهور المكونات والنصائح على الشاشة.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['طبخ', 'وصفة', 'فيديو سريع'],
    created_at: '2024-07-24T19:00:00Z',
    likes: 290,
    views: 1100,
  },
  {
    id: 'prompt-24',
    title: 'مقدمة (Intro) لقناة يوتيوب تقنية',
    prompt_text: 'مقدمة فيديو متحركة (animated intro) مدتها 5 ثوانٍ لقناة يوتيوب تقنية. يجب أن تظهر فيها خطوط إلكترونية متوهجة تتجمع لتشكل شعار القناة.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['موشن جرافيك', 'يوتيوب', 'مقدمة'],
    created_at: '2024-07-24T16:00:00Z',
    likes: 210,
    views: 850,
    verified: true,
  },
  {
    id: 'prompt-25',
    title: 'لقطة درون لمدينة دبي ليلاً',
    prompt_text: 'لقطة جوية بطائرة درون (drone shot) لشارع الشيخ زايد في دبي ليلاً، تظهر الأضواء السريعة للسيارات وناطحات السحاب المضيئة. hyperlapse, cinematic, 4k.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['درون', 'دبي', 'hyperlapse'],
    created_at: '2024-07-23T22:00:00Z',
    likes: 550,
    views: 2000,
  },
  {
    id: 'prompt-26',
    title: 'فيديو رسوم متحركة يشرح تقنية البلوك تشين',
    prompt_text: 'فيديو رسوم متحركة توضيحي (explainer video) مدته 90 ثانية، يشرح مفهوم البلوك تشين بطريقة مبسطة باستخدام أيقونات ورسوم بيانية سهلة الفهم.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['رسوم متحركة', 'تعليمي', 'بلوك تشين'],
    created_at: '2024-07-23T14:00:00Z',
    likes: 320,
    views: 1300,
  },
  {
    id: 'prompt-27',
    title: 'مشهد قطة تلعب بكرة صوف ببطء',
    prompt_text: 'مشهد فيديو بطيء الحركة (slow motion) لقطة صغيرة تلعب بكرة من الصوف الأحمر، مع التركيز على تفاصيل الفرو وحركة القطة.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[0],
    tags: ['حركة بطيئة', 'حيوانات', 'لطيف'],
    created_at: '2024-07-22T18:00:00Z',
    likes: 260,
    views: 980,
    verified: true,
  },
  {
    id: 'prompt-28',
    title: 'فيديو تاريخي عن بناء الأهرامات',
    prompt_text: 'فيديو قصير يعيد تصور بناء الأهرامات في مصر القديمة، باستخدام لقطات سينمائية تظهر آلاف العمال وهم ينقلون الحجارة الضخمة. أسلوب وثائقي.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تاريخ', 'وثائقي', 'مصر القديمة'],
    created_at: '2024-07-22T11:00:00Z',
    likes: 480,
    views: 1800,
  },
  {
    id: 'prompt-29',
    title: 'جولة افتراضية في سوق واقف بقطر',
    prompt_text: 'فيديو بنمط جولة افتراضية (virtual tour) في سوق واقف بقطر، يمر بالكاميرا عبر الأزقة الضيقة والمتاجر التقليدية، مع أصوات السوق المحيطة.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['جولة افتراضية', 'سفر', 'قطر'],
    created_at: '2024-07-21T20:00:00Z',
    likes: 340,
    views: 1250,
  },
  {
    id: 'prompt-30',
    title: 'تأثير قطرة ماء تسقط في بركة',
    prompt_text: 'فيديو مقرب جداً (extreme close-up) يظهر قطرة ماء تسقط في بركة هادئة، مع تموجات تنتشر ببطء. ultra high speed camera effect.',
    category: PromptCategory.VIDEO,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['مقرب', 'طبيعة', 'تأثيرات بصرية'],
    created_at: '2024-07-21T15:00:00Z',
    likes: 400,
    views: 1600,
    verified: true,
  },

  // === CODE Prompts (10) ===
  {
    id: 'prompt-31',
    title: 'مكون React لعرض بطاقة مستخدم',
    prompt_text: 'اكتب كود مكون React باستخدام TypeScript و Tailwind CSS لإنشاء بطاقة مستخدم تعرض صورة رمزية، اسم المستخدم، ورابط للملف الشخصي.',
    category: PromptCategory.CODE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['React', 'TypeScript', 'Tailwind CSS'],
    created_at: '2024-07-25T12:00:00Z',
    likes: 89,
    views: 320,
    verified: true,
  },
  {
    id: 'prompt-32',
    title: 'سكربت Python لتحليل بيانات CSV',
    prompt_text: 'اكتب سكربت Python يستخدم مكتبة Pandas لقراءة ملف CSV يحتوي على بيانات مبيعات، ثم حساب إجمالي المبيعات لكل منتج وعرض النتائج.',
    category: PromptCategory.CODE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['Python', 'Pandas', 'تحليل بيانات'],
    created_at: '2024-07-25T09:00:00Z',
    likes: 150,
    views: 600,
  },
  {
    id: 'prompt-33',
    title: 'استعلام SQL لجلب العملاء الأكثر نشاطًا',
    prompt_text: 'اكتب استعلام SQL لجلب أفضل 10 عملاء من جدول "Orders" بناءً على إجمالي قيمة طلباتهم في العام الماضي.',
    category: PromptCategory.CODE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['SQL', 'قواعد بيانات', 'تحليل'],
    created_at: '2024-07-24T17:00:00Z',
    likes: 110,
    views: 450,
  },
  {
    id: 'prompt-34',
    title: 'إنشاء دالة JavaScript للتحقق من صحة البريد الإلكتروني',
    prompt_text: 'اكتب دالة JavaScript تستخدم تعابير النمطية (Regex) للتحقق مما إذا كانت السلسلة النصية المُدخلة عبارة عن عنوان بريد إلكتروني صالح.',
    category: PromptCategory.CODE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['JavaScript', 'Regex', 'تحقق'],
    created_at: '2024-07-24T11:00:00Z',
    likes: 95,
    views: 400,
    verified: true,
  },
  {
    id: 'prompt-35',
    title: 'كود CSS لإنشاء زر بتأثير حركي',
    prompt_text: 'اكتب كود CSS لإنشاء زر يتغير لونه تدريجيًا ويظهر له ظل عند مرور مؤشر الفأرة فوقه (hover effect).',
    category: PromptCategory.CODE,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['CSS', 'تأثيرات', 'واجهة مستخدم'],
    created_at: '2024-07-23T15:00:00Z',
    likes: 130,
    views: 550,
  },
  {
    id: 'prompt-36',
    title: 'إنشاء API بسيط باستخدام Node.js و Express',
    prompt_text: 'اكتب كود لإنشاء خادم ويب بسيط باستخدام Node.js و Express يحتوي على نقطة نهاية (endpoint) واحدة من نوع GET على المسار /api/users وتعيد قائمة وهمية من المستخدمين بصيغة JSON.',
    category: PromptCategory.CODE,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['Node.js', 'Express', 'API', 'Backend'],
    created_at: '2024-07-23T10:00:00Z',
    likes: 200,
    views: 800,
  },
  {
    id: 'prompt-37',
    title: 'خوارزمية الفرز السريع (Quicksort) بلغة C++',
    prompt_text: 'قم بتنفيذ خوارزمية الفرز السريع (Quicksort) في لغة C++ لفرز مصفوفة من الأعداد الصحيحة.',
    category: PromptCategory.CODE,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['C++', 'خوارزميات', 'هياكل بيانات'],
    created_at: '2024-07-22T16:00:00Z',
    likes: 180,
    views: 750,
  },
  {
    id: 'prompt-38',
    title: 'إصلاح خطأ في دالة Python',
    prompt_text: 'الدالة التالية في Python لا تعمل كما هو متوقع. اشرح سبب الخطأ وقدم النسخة المصححة. الكود: def calculate_average(numbers): total = 0 for n in numbers: total += n return total / len(numbers) - 1',
    category: PromptCategory.CODE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['Python', 'تصحيح أخطاء', 'debugging'],
    created_at: '2024-07-22T09:00:00Z',
    likes: 75,
    views: 300,
    verified: true,
  },
  {
    id: 'prompt-39',
    title: 'استخدام Fetch API في JavaScript لجلب بيانات',
    prompt_text: 'اكتب دالة JavaScript غير متزامنة (async/await) تستخدم Fetch API لجلب بيانات من عنوان URL وهمي (https://jsonplaceholder.typicode.com/todos/1) ثم طباعة العنوان (title) في الكونسول.',
    category: PromptCategory.CODE,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['JavaScript', 'API', 'async'],
    created_at: '2024-07-21T17:00:00Z',
    likes: 160,
    views: 650,
  },
  {
    id: 'prompt-40',
    title: 'إنشاء Dockerfile لتطبيق Flask',
    prompt_text: 'اكتب Dockerfile لإنشاء حاوية (container) لتطبيق ويب بسيط مبني باستخدام Flask في Python. يجب أن يتضمن تثبيت الاعتماديات من ملف requirements.txt وتشغيل التطبيق.',
    // FIX: The category was incorrect and the level was missing.
    category: PromptCategory.CODE,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['Docker', 'Flask', 'DevOps'],
    created_at: '2024-07-21T11:00:00Z',
    likes: 220,
    views: 900,
    verified: true,
  },

    // === WRITING Prompts (10) ===
  {
    id: 'prompt-41',
    title: 'وصف مدينة مستقبلية بأسلوب السايبربانك',
    prompt_text: 'صف مدينة عربية مستقبلية في عام 2077، بأسلوب السايبربانك، مع التركيز على الأسواق الليلية المضاءة بالنيون، المركبات الطائرة، والأبراج الشاهقة الممزوجة بالعمارة التقليدية.',
    category: PromptCategory.WRITING,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['سايبربانك', 'كتابة إبداعية', 'خيال علمي'],
    created_at: '2024-07-25T10:00:00Z',
    likes: 132,
    views: 540,
    verified: true,
  },
  {
    id: 'prompt-42',
    title: 'كتابة مقال قصير عن أهمية إعادة التدوير',
    prompt_text: 'اكتب مقالًا من 500 كلمة حول أهمية إعادة التدوير للحفاظ على البيئة، مع ذكر أمثلة عملية يمكن للأفراد تطبيقها في حياتهم اليومية.',
    category: PromptCategory.WRITING,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['مقالات', 'بيئة', 'إعادة تدوير'],
    created_at: '2024-07-25T08:00:00Z',
    likes: 95,
    views: 400,
  },
  {
    id: 'prompt-43',
    title: 'إنشاء قصة قصيرة للأطفال قبل النوم',
    prompt_text: 'اكتب قصة قصيرة للأطفال (5-7 سنوات) عن سنجاب صغير شجاع يتعلم أهمية مشاركة الجوز مع أصدقائه في الغابة.',
    category: PromptCategory.WRITING,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['قصص أطفال', 'كتابة إبداعية'],
    created_at: '2024-07-24T20:00:00Z',
    likes: 180,
    views: 720,
  },
  {
    id: 'prompt-44',
    title: 'كتابة نص إعلاني (copy) لمنتج سماعات لاسلكية',
    prompt_text: 'اكتب نصًا إعلانيًا قصيرًا وجذابًا لصفحة منتج سماعات لاسلكية جديدة. ركز على ميزات مثل "عزل الضوضاء الفائق" و "بطارية تدوم 24 ساعة".',
    category: PromptCategory.WRITING,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['كتابة إعلانية', 'تسويق', 'copywriting'],
    created_at: '2024-07-24T13:00:00Z',
    likes: 220,
    views: 900,
    verified: true,
  },
  {
    id: 'prompt-45',
    title: 'صياغة منشور لوسائل التواصل الاجتماعي عن إطلاق منتج',
    prompt_text: 'اكتب منشورًا لمنصة انستغرام يعلن عن إطلاق تطبيق جديد لإدارة المهام. استخدم لغة حماسية، إيموجي، ودعوة واضحة للمستخدمين لتحميل التطبيق.',
    category: PromptCategory.WRITING,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['سوشيال ميديا', 'تسويق', 'إطلاق منتج'],
    created_at: '2024-07-23T18:00:00Z',
    likes: 150,
    views: 650,
  },
  {
    id: 'prompt-46',
    title: 'كتابة سيناريو لفيديو يوتيوب مدته 5 دقائق',
    prompt_text: 'اكتب سيناريو لفيديو يوتيوب مدته 5 دقائق بعنوان "5 أخطاء شائعة يرتكبها المبتدئون في الاستثمار". يجب أن يتضمن مقدمة، 5 نقاط رئيسية، وخاتمة.',
    category: PromptCategory.WRITING,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['سيناريو', 'يوتيوب', 'استثمار'],
    created_at: '2024-07-23T11:00:00Z',
    likes: 280,
    views: 1150,
  },
  {
    id: 'prompt-47',
    title: 'إنشاء صفحة "من نحن" لشركة ناشئة',
    prompt_text: 'اكتب محتوى صفحة "من نحن" لشركة ناشئة في مجال التكنولوجيا التعليمية. يجب أن يروي المحتوى قصة الشركة، رؤيتها، ومهمتها بطريقة ملهمة وموثوقة.',
    category: PromptCategory.WRITING,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['محتوى ويب', 'من نحن', 'قصة علامة تجارية'],
    created_at: '2024-07-22T15:00:00Z',
    likes: 190,
    views: 800,
    verified: true,
  },
  {
    id: 'prompt-48',
    title: 'كتابة قصيدة عن جمال الصحراء ليلاً',
    prompt_text: 'اكتب قصيدة من 12 بيتاً تصف جمال وهدوء الصحراء العربية في ليلة مقمرة، مع التركيز على النجوم الساطعة والصمت المهيب.',
    category: PromptCategory.WRITING,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['شعر', 'كتابة إبداعية', 'طبيعة'],
    created_at: '2024-07-22T09:00:00Z',
    likes: 250,
    views: 950,
  },
  {
    id: 'prompt-49',
    title: 'وصف منتج لمتجر إلكتروني يبيع العسل الطبيعي',
    prompt_text: 'اكتب وصف منتج جذاب لمتجر إلكتروني يبيع عسل السدر الطبيعي. سلط الضوء على فوائده الصحية، مصدره، ومذاقه الفريد.',
    category: PromptCategory.WRITING,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['وصف منتج', 'تجارة إلكترونية', 'تسويق'],
    created_at: '2024-07-21T14:00:00Z',
    likes: 160,
    views: 700,
  },
  {
    id: 'prompt-50',
    title: 'كتابة فصل من رواية غموض',
    prompt_text: 'اكتب الفصل الأول من رواية غموض تدور أحداثها في فندق قديم على شاطئ البحر، حيث يكتشف المحقق "عادل" رسالة غامضة بجانب جثة الضحية.',
    category: PromptCategory.WRITING,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['رواية', 'غموض', 'كتابة إبداعية'],
    created_at: '2024-07-21T10:00:00Z',
    likes: 320,
    views: 1300,
    verified: true,
  },

  // === BUSINESS Prompts (10) ===
  {
    id: 'prompt-51',
    title: 'خطة عمل لشركة ناشئة',
    prompt_text: 'أنشئ خطة عمل مفصلة لشركة ناشئة في مجال التكنولوجيا المالية (Fintech) تستهدف السوق السعودي، مع تحديد الجمهور المستهدف، ونموذج الإيرادات، واستراتيجية التسويق.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['أعمال', 'تخطيط', 'fintech'],
    created_at: '2024-07-25T11:00:00Z',
    likes: 92,
    views: 450,
    verified: true,
  },
  {
    id: 'prompt-52',
    title: 'تحليل SWOT لمطعم جديد',
    prompt_text: 'قم بإجراء تحليل SWOT (نقاط القوة، الضعف، الفرص، التهديدات) لمطعم جديد يقدم المأكولات الصحية في مدينة كبيرة.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تحليل SWOT', 'استراتيجية', 'أعمال'],
    created_at: '2024-07-25T09:00:00Z',
    likes: 120,
    views: 500,
  },
  {
    id: 'prompt-53',
    title: 'صياغة بيان مهمة ورؤية لشركة',
    prompt_text: 'اكتب بيان المهمة (Mission Statement) وبيان الرؤية (Vision Statement) لشركة استشارات تقنية تركز على مساعدة الشركات الصغيرة على التحول الرقمي.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['استراتيجية', 'مهمة ورؤية', 'علامة تجارية'],
    created_at: '2024-07-24T15:00:00Z',
    likes: 150,
    views: 600,
  },
  {
    id: 'prompt-54',
    title: 'إنشاء استبيان لقياس رضا العملاء',
    prompt_text: 'صمم استبيانًا من 10 أسئلة لقياس رضا العملاء عن خدمة توصيل الطعام. يجب أن يتضمن أسئلة حول سرعة التوصيل، جودة الطعام، وتجربة التطبيق.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['استبيان', 'رضا العملاء', 'بحث سوقي'],
    created_at: '2024-07-24T10:00:00Z',
    likes: 80,
    views: 350,
  },
  {
    id: 'prompt-55',
    title: 'تحديد شخصيات العملاء (Personas) لمتجر أزياء',
    prompt_text: 'أنشئ ثلاث شخصيات عملاء (Buyer Personas) مفصلة لمتجر إلكتروني يبيع أزياء عصرية للنساء الذين تتراوح أعمارهم بين 25 و 40 عامًا.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تسويق', 'شخصية العميل', 'استراتيجية'],
    created_at: '2024-07-23T17:00:00Z',
    likes: 170,
    views: 700,
    verified: true,
  },
  {
    id: 'prompt-56',
    title: 'كتابة بيان صحفي لإطلاق منتج',
    prompt_text: 'اكتب بيانًا صحفيًا مهنيًا يعلن عن إطلاق تطبيق جوال جديد لتعلم اللغات. يجب أن يتضمن عنوانًا جذابًا، ملخصًا، اقتباسًا من المدير التنفيذي، ومعلومات عن الشركة.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['علاقات عامة', 'بيان صحفي', 'إطلاق منتج'],
    created_at: '2024-07-23T12:00:00Z',
    likes: 110,
    views: 480,
  },
  {
    id: 'prompt-57',
    title: 'توليد أفكار لحملة تسويقية في رمضان',
    prompt_text: 'اقترح 5 أفكار إبداعية لحملة تسويق رقمي لعلامة تجارية للمشروبات خلال شهر رمضان، تستهدف العائلات والشباب.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تسويق', 'حملة إعلانية', 'رمضان'],
    created_at: '2024-07-22T14:00:00Z',
    likes: 200,
    views: 850,
  },
  {
    id: 'prompt-58',
    title: 'تحليل المنافسين في سوق تطبيقات التوصيل',
    prompt_text: 'قم بإعداد جدول تحليل للمنافسين الرئيسيين (مثل أوبر إيتس وهنقرستيشن) في سوق تطبيقات توصيل الطعام، وقارن بينهم من حيث الميزات، الأسعار، والحصة السوقية.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تحليل تنافسي', 'استراتيجية', 'بحث سوقي'],
    created_at: '2024-07-22T10:00:00Z',
    likes: 160,
    views: 650,
    verified: true,
  },
  {
    id: 'prompt-59',
    title: 'عرض قيمة فريد (UVP) لخدمة استشارات',
    prompt_text: 'صغ عرض قيمة فريد (Unique Value Proposition) واضح ومقنع لخدمة استشارات تساعد الشركات على تحسين تواجدها على وسائل التواصل الاجتماعي.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تسويق', 'UVP', 'استراتيجية'],
    created_at: '2024-07-21T16:00:00Z',
    likes: 130,
    views: 520,
  },
  {
    id: 'prompt-60',
    title: 'سيناريو تدريب لخدمة العملاء',
    prompt_text: 'اكتب سيناريو لعب أدوار لتدريب موظفي خدمة العملاء على كيفية التعامل مع عميل غاضب يشكو من تأخر طلبه.',
    category: PromptCategory.BUSINESS,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['خدمة عملاء', 'تدريب', 'سيناريو'],
    created_at: '2024-07-21T11:00:00Z',
    likes: 90,
    views: 400,
  },
  
    // === ART Prompts (10) ===
  {
    id: 'prompt-61',
    title: 'رسمة حصان عربي أصيل',
    prompt_text: 'رسمة فنية بأسلوب الألوان المائية لحصان عربي أصيل يركض بحرية في حقل أخضر، مع التركيز على حركة الشعر والذيل.',
    category: PromptCategory.ART,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['فن', 'ألوان مائية', 'حصان'],
    created_at: '2024-07-25T09:00:00Z',
    likes: 175,
    views: 610,
    verified: true,
  },
  {
    id: 'prompt-62',
    title: 'مشهد سريالي لكوكب زحل',
    prompt_text: 'لوحة فنية سريالية لكوكب زحل بحلقات مصنوعة من الكتب القديمة، تسبح حوله حيتان مضيئة في الفضاء. a surreal masterpiece, oil on canvas, highly detailed.',
    category: PromptCategory.ART,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['سريالية', 'فن', 'فضاء', 'خيال'],
    created_at: '2024-07-25T07:00:00Z',
    likes: 380,
    views: 1400,
  },
  {
    id: 'prompt-63',
    title: 'فن تجريدي يمثل مشاعر الفرح',
    prompt_text: 'لوحة فنية تجريدية (abstract art) تعبر عن مشاعر الفرح والسعادة، باستخدام ألوان دافئة ومشرقة مثل الأصفر والبرتقالي، مع أشكال ديناميكية وانفجارات لونية.',
    category: PromptCategory.ART,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['فن تجريدي', 'مشاعر', 'ألوان'],
    created_at: '2024-07-24T18:00:00Z',
    likes: 210,
    views: 850,
  },
  {
    id: 'prompt-64',
    title: 'بورتريه بأسلوب فن البوب (Pop Art)',
    prompt_text: 'بورتريه لامرأة عربية بأسلوب فن البوب على طريقة آندي وارهول، باستخدام ألوان زاهية ومتناقضة وخلفية منقطة.',
    category: PromptCategory.ART,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['فن البوب', 'بورتريه', 'فن حديث'],
    created_at: '2024-07-24T14:00:00Z',
    likes: 250,
    views: 950,
    verified: true,
  },
  {
    id: 'prompt-65',
    title: 'مخلوق أسطوري من الفولكلور العربي',
    prompt_text: 'تصور فني لمخلوق "الغول" من الفولكلور العربي، بأسلوب فن خيالي مظلم (dark fantasy art). يجب أن يكون المخلوق ضخمًا ومخيفًا، بعيون متوهجة، ويظهر في كهف مظلم.',
    category: PromptCategory.ART,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['فن خيالي', 'مخلوقات', 'أسطورة'],
    created_at: '2024-07-23T20:00:00Z',
    likes: 320,
    views: 1200,
  },
  {
    id: 'prompt-66',
    title: 'فن الخط العربي بكلمة "سلام"',
    prompt_text: 'قطعة فنية للخط العربي (calligraphy) لكلمة "سلام" مكتوبة بخط الثلث، مع زخارف نباتية متداخلة بألوان مائية هادئة.',
    category: PromptCategory.ART,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['خط عربي', 'فن إسلامي', 'سلام'],
    created_at: '2024-07-23T15:00:00Z',
    likes: 400,
    views: 1500,
    verified: true,
  },
  {
    id: 'prompt-67',
    title: 'مدينة ملاهي مهجورة في غابة',
    prompt_text: 'فن البيئة (environment concept art) لمدينة ملاهي مهجورة ومغطاة بالنباتات المتسلقة داخل غابة كثيفة، مع ضوء خافت يتسلل عبر الأشجار. moody, atmospheric, abandoned.',
    category: PromptCategory.ART,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['فن مفاهيمي', 'بيئة', 'مهجور'],
    created_at: '2024-07-22T19:00:00Z',
    likes: 290,
    views: 1100,
  },
  {
    id: 'prompt-68',
    title: 'رسمة بأسلوب فن البيكسل (Pixel Art) لسوق شعبي',
    prompt_text: 'مشهد بأسلوب فن البيكسل (pixel art) لسوق شعبي عربي مزدحم، يظهر الباعة والمارة وتفاصيل صغيرة مثل الفواكه والسجاد. isometric view, vibrant colors.',
    category: PromptCategory.ART,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['فن البيكسل', 'مشهد', 'isometric'],
    created_at: '2024-07-22T12:00:00Z',
    likes: 260,
    views: 1000,
  },
  {
    id: 'prompt-69',
    title: 'غابة مسحورة ومضيئة ليلاً',
    prompt_text: 'لوحة فنية لغابة مسحورة ليلاً، حيث تتوهج الفطريات والأزهار بألوان النيون، ونهر متلألئ يمر عبرها. fantasy landscape, bioluminescent, magical.',
    category: PromptCategory.ART,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[0],
    tags: ['فن خيالي', 'طبيعة', 'سحري'],
    created_at: '2024-07-21T21:00:00Z',
    likes: 450,
    views: 1800,
    verified: true,
  },
  {
    id: 'prompt-70',
    title: 'رسم تخطيطي (sketch) معماري لمسجد حديث',
    prompt_text: 'رسم تخطيطي معماري بقلم الرصاص (pencil sketch) لمسجد بتصميم حديث، يتميز بقبة زجاجية ومئذنة ذات تصميم مبتكر.',
    category: PromptCategory.ART,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['رسم', 'عمارة', 'مسجد', 'تخطيط'],
    created_at: '2024-07-21T15:00:00Z',
    likes: 190,
    views: 750,
  },
  
  // === DESIGN Prompts (10) ===
  {
    id: 'prompt-71',
    title: 'تصميم شعار لعلامة تجارية للقهوة',
    prompt_text: 'صمم شعارًا حديثًا وبسيطًا لعلامة تجارية جديدة للقهوة المختصة اسمها "ذوق". يجب أن يكون الشعار مناسبًا للاستخدام على الأكواب والتغليف ووسائل التواصل الاجتماعي.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تصميم', 'شعار', 'هوية بصرية'],
    created_at: '2024-07-25T14:20:00Z',
    likes: 204,
    views: 780,
    verified: true,
  },
  {
    id: 'prompt-72',
    title: 'تصميم واجهة مستخدم لتطبيق سفر',
    prompt_text: 'تصميم واجهة المستخدم (UI design) للشاشة الرئيسية لتطبيق حجز رحلات سفر. يجب أن تحتوي على شريط بحث للوجهات، قسم للعروض المميزة، وأيقونات للرحلات الجوية والفنادق والسيارات. modern, clean, user-friendly.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['UI/UX', 'تصميم تطبيقات', 'سفر'],
    created_at: '2024-07-25T10:00:00Z',
    likes: 310,
    views: 1200,
  },
  {
    id: 'prompt-73',
    title: 'تصميم صفحة هبوط لمؤتمر تقني',
    prompt_text: 'تصميم صفحة هبوط (landing page) لمؤتمر تقني قادم. يجب أن تكون جذابة بصريًا، وتحتوي على معلومات عن المتحدثين، جدول الأعمال، وزر بارز للتسجيل.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تصميم ويب', 'صفحة هبوط', 'UI'],
    created_at: '2024-07-24T16:00:00Z',
    likes: 240,
    views: 900,
  },
  {
    id: 'prompt-74',
    title: 'إنشاء لوحة ألوان (color palette) لعلامة تجارية صديقة للبيئة',
    prompt_text: 'أنشئ لوحة ألوان مكونة من 5 ألوان لعلامة تجارية تبيع منتجات صديقة للبيئة. يجب أن توحي الألوان بالطبيعة والاستدامة.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[1],
    tags: ['تصميم', 'ألوان', 'هوية بصرية'],
    created_at: '2024-07-24T12:00:00Z',
    likes: 150,
    views: 600,
    verified: true,
  },
  {
    id: 'prompt-75',
    title: 'تصميم انفوجرافيك عن فوائد النوم الجيد',
    prompt_text: 'تصميم انفوجرافيك (infographic) يوضح الفوائد الصحية للنوم الجيد، باستخدام أيقونات ورسوم بيانية بسيطة لتمثيل المعلومات مثل تحسين الذاكرة وتقوية المناعة.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['انفوجرافيك', 'تصميم بيانات', 'صحة'],
    created_at: '2024-07-23T18:00:00Z',
    likes: 280,
    views: 1100,
  },
  {
    id: 'prompt-76',
    title: 'تصميم غلاف بودكاست عن ريادة الأعمال',
    prompt_text: 'تصميم غلاف (cover art) لبودكاست اسمه "خطوة البداية" يناقش ريادة الأعمال. استخدم تصميمًا جريئًا واحترافيًا مع خطوط واضحة وأيقونة ترمز إلى النمو والنجاح.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.BEGINNER,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['تصميم جرافيك', 'بودكاست', 'ريادة أعمال'],
    created_at: '2024-07-23T14:00:00Z',
    likes: 190,
    views: 750,
  },
  {
    id: 'prompt-77',
    title: 'تصميم نموذج بطاقة عمل (Business Card) لمصور',
    prompt_text: 'تصميم بطاقة عمل عصرية لمصور فوتوغرافي. يجب أن تكون البطاقة ذات تصميم بسيط، تعرض الشعار واسم المصور على جانب، ومعلومات الاتصال ومثال صغير لأعماله على الجانب الآخر.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.ARABIC,
    author: mockUsers[0],
    tags: ['تصميم طباعة', 'بطاقة عمل', 'هوية'],
    created_at: '2024-07-22T17:00:00Z',
    likes: 210,
    views: 820,
    verified: true,
  },
  {
    id: 'prompt-78',
    title: 'إعادة تصميم شعار قديم لجعله عصريًا',
    prompt_text: 'خذ شعار شركة [اذكر اسم شركة قديمة أو صف الشعار] وأعد تصميمه ليصبح أكثر بساطة وعصرية وملاءمة للعصر الرقمي. اشرح التغييرات التي قمت بها.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.EXPERT,
    language: PromptLanguage.ARABIC,
    author: mockUsers[1],
    tags: ['إعادة تصميم', 'شعار', 'تحديث علامة تجارية'],
    created_at: '2024-07-22T11:00:00Z',
    likes: 350,
    views: 1300,
  },
  {
    id: 'prompt-79',
    title: 'تصميم مجموعة ملصقات (stickers) لتطبيق محادثة',
    prompt_text: 'صمم مجموعة من 4 ملصقات رقمية (stickers) لتطبيق محادثة، تعبر عن ردود فعل شائعة مثل (مضحك، رائع، حزين، موافق). يجب أن تكون بأسلوب كرتوني لطيف.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.INTERMEDIATE,
    language: PromptLanguage.MULTILINGUAL,
    author: mockUsers[0],
    tags: ['ملصقات', 'تصميم شخصيات', 'توضيح'],
    created_at: '2024-07-21T18:00:00Z',
    likes: 260,
    views: 980,
  },
  {
    id: 'prompt-80',
    title: 'تصميم واجهة ساعة ذكية لعرض النشاط البدني',
    prompt_text: 'تصميم واجهة ساعة ذكية (watch face) تعرض بيانات النشاط البدني اليومي. يجب أن تعرض بوضوح عدد الخطوات، معدل ضربات القلب، والسعرات الحرارية المحروقة بطريقة جذابة وسهلة القراءة.',
    category: PromptCategory.DESIGN,
    level: PromptLevel.ADVANCED,
    language: PromptLanguage.ENGLISH,
    author: mockUsers[1],
    tags: ['UI/UX', 'تصميم واجهات', 'ساعة ذكية'],
    created_at: '2024-07-21T13:00:00Z',
    likes: 290,
    views: 1150,
    verified: true,
  },
];


export const mockPosts: Post[] = [
  {
    id: 'post-1',
    title: 'كيف تكتب أوامر فعالة لنماذج الذكاء الاصطناعي؟',
    slug: 'how-to-write-effective-prompts',
    content_html: `
      <h2>مقدمة</h2>
      <p>كتابة الأوامر (Prompts) هي فن وعلم في نفس الوقت. الأمر الجيد يمكن أن يكون الفارق بين نتيجة مذهلة ونتيجة غير مفيدة على الإطلاق. في هذا المقال، سنستعرض بعض النصائح الأساسية لكتابة أوامر فعالة.</p>
      <h3>1. كن واضحًا ومحددًا</h3>
      <p>كلما كان أمرك أكثر تحديدًا، كانت النتيجة أفضل. بدلاً من أن تقول "اكتب عن السيارات"، جرب "اكتب مقالًا قصيرًا عن تاريخ السيارات الكهربائية وتأثيرها على البيئة".</p>
      <h3>2. قدم سياقًا كافيًا</h3>
      <p>يحتاج النموذج إلى سياق لفهم ما تطلبه. إذا كنت تريد كتابة قصة، فحدد الشخصيات، المكان، والزمان.</p>
      <ul>
        <li><strong>الشخصية الرئيسية:</strong> مغامر شاب</li>
        <li><strong>المكان:</strong> مدينة قديمة مفقودة في الأمازون</li>
        <li><strong>الهدف:</strong> البحث عن كنز أسطوري</li>
      </ul>
      <h3>3. استخدم أمثلة</h3>
      <p>إذا كنت تريد أسلوبًا معينًا، قدم مثالاً. "اكتب وصفًا للمنتج بأسلوب مرح وودود، مثل أسلوب شركة Innocent Drinks".</p>
      <h2>خاتمة</h2>
      <p>الممارسة هي المفتاح. جرب صيغًا مختلفة، ولا تخف من التجربة حتى تصل إلى أفضل النتائج.</p>
    `,
    author: mockUsers[1],
    published_at: '2024-07-15T11:00:00Z',
    featured_image: 'https://picsum.photos/seed/post1/600/400',
    is_trending: true,
    tags: ['أساسيات', 'هندسة الأوامر', 'نصائح'],
    views: 1500,
    comments_count: 12,
  },
  {
    id: 'post-2',
    title: 'استخدام الذكاء الاصطناعي في توليد الصور',
    slug: 'using-ai-for-image-generation',
    content_html: `
      <h2>ثورة توليد الصور</h2>
      <p>أصبحت نماذج الذكاء الاصطناعي قادرة على توليد صور واقعية ومبتكرة من مجرد وصف نصي. هذا يفتح آفاقًا جديدة للفنانين والمصممين ومنشئي المحتوى.</p>
      <h3>نصائح لأوامر الصور</h3>
      <ul>
        <li><strong>وصف التفاصيل:</strong> لا تكتفِ بـ "سيارة حمراء". جرب "سيارة رياضية حمراء لامعة من طراز فيراري، تقف على طريق ساحلي عند غروب الشمس، مع انعكاسات على هيكلها".</li>
        <li><strong>حدد الأسلوب:</strong> يمكنك طلب أساليب فنية مختلفة مثل "بأسلوب فان جوخ"، "صورة فوتوغرافية واقعية"، "فن رقمي"، "أسلوب الأنيمي".</li>
        <li><strong>حدد الإضاءة والكاميرا:</strong> جرب "إضاءة درامية"، "لقطة واسعة"، "عدسة 50mm" للحصول على نتائج أكثر احترافية.</li>
      </ul>
      <p>استمتع بالإبداع!</p>
    `,
    author: mockUsers[0],
    published_at: '2024-07-10T09:00:00Z',
    featured_image: 'https://picsum.photos/seed/post2/600/400',
    is_trending: false,
    tags: ['توليد الصور', 'Midjourney', 'DALL-E'],
    views: 2300,
    comments_count: 8,
  },
  {
    id: 'post-3',
    title: 'تقنيات هندسة الأوامر المتقدمة: ما وراء الأساسيات',
    slug: 'advanced-prompt-engineering',
    content_html: '<p>تعمق في تقنيات مثل Chain-of-Thought و Few-shot learning للحصول على استجابات أكثر دقة وتعقيدًا من نماذج اللغة.</p>',
    author: mockUsers[0],
    published_at: '2024-07-20T14:00:00Z',
    featured_image: 'https://picsum.photos/seed/post3/600/400',
    is_trending: true,
    tags: ['هندسة الأوامر', 'متقدم', 'تقنية'],
    views: 2800,
    comments_count: 25,
  },
  {
    id: 'post-4',
    title: 'ثورة الفيديو: كيف تنشئ مقاطع مذهلة باستخدام الذكاء الاصطناعي؟',
    slug: 'ai-video-creation',
    content_html: '<p>استكشف أحدث أدوات توليد الفيديو بالذكاء الاصطناعي مثل Veo و Sora. تعلم كيفية كتابة الأوامر التي تنتج لقطات سينمائية.</p>',
    author: mockUsers[1],
    published_at: '2024-07-18T10:00:00Z',
    featured_image: 'https://picsum.photos/seed/post4/600/400',
    is_trending: false,
    tags: ['فيديو', 'Veo', 'Sora', 'إبداع'],
    views: 1900,
    comments_count: 15,
  },
  {
    id: 'post-5',
    title: 'المبرمج الخارق: 5 طرق لاستخدام AI لزيادة إنتاجيتك',
    slug: 'ai-for-coding-productivity',
    content_html: '<p>من إكمال الكود وتصحيح الأخطاء إلى كتابة الاختبارات، اكتشف كيف يمكن لمساعدي البرمجة بالذكاء الاصطناعي أن يجعلوك مبرمجًا أفضل وأسرع.</p>',
    author: mockUsers[0],
    published_at: '2024-07-16T12:00:00Z',
    featured_image: 'https://picsum.photos/seed/post5/600/400',
    is_trending: false,
    tags: ['برمجة', 'إنتاجية', 'Copilot'],
    views: 2100,
    comments_count: 18,
  },
  {
    id: 'post-6',
    title: 'الذكاء الاصطناعي في التسويق: أتمتة وتحليل',
    slug: 'ai-in-marketing',
    content_html: '<p>تعلم كيف يمكن للذكاء الاصطناعي مساعدتك في كتابة نصوص إعلانية، تحليل بيانات العملاء، وتخصيص حملاتك التسويقية لتحقيق أفضل النتائج.</p>',
    author: mockUsers[1],
    published_at: '2024-07-14T09:00:00Z',
    featured_image: 'https://picsum.photos/seed/post6/600/400',
    is_trending: false,
    tags: ['تسويق', 'أعمال', 'بيانات'],
    views: 1600,
    comments_count: 11,
  },
  {
    id: 'post-7',
    title: 'فن كتابة القصة بالذكاء الاصطناعي: من الفكرة إلى الفصل الأول',
    slug: 'ai-story-writing',
    content_html: '<p>استخدم الذكاء الاصطناعي كشريك إبداعي لتطوير الشخصيات، بناء العوالم، وكتابة حبكات مثيرة. نصائح عملية للروائيين وكتاب السيناريو.</p>',
    author: mockUsers[0],
    published_at: '2024-07-12T15:00:00Z',
    featured_image: 'https://picsum.photos/seed/post7/600/400',
    is_trending: false,
    tags: ['كتابة', 'إبداع', 'قصص'],
    views: 1450,
    comments_count: 22,
  },
  {
    id: 'post-8',
    title: 'فهم نماذج الانتشار (Diffusion Models): السحر وراء توليد الصور',
    slug: 'understanding-diffusion-models',
    content_html: '<p>شرح مبسط لكيفية عمل نماذج توليد الصور مثل DALL-E و Midjourney، وكيف تحول الضوضاء العشوائية إلى أعمال فنية مذهلة.</p>',
    author: mockUsers[1],
    published_at: '2024-07-11T11:00:00Z',
    featured_image: 'https://picsum.photos/seed/post8/600/400',
    is_trending: false,
    tags: ['تقنية', 'توليد الصور', 'شرح'],
    views: 1800,
    comments_count: 9,
  },
  {
    id: 'post-9',
    title: 'أخلاقيات الذكاء الاصطناعي: كيف نستخدم هذه القوة بمسؤولية؟',
    slug: 'ai-ethics',
    content_html: '<p>نقاش حول التحديات الأخلاقية التي يطرحها الذكاء الاصطناعي، من التحيز في البيانات إلى الخصوصية ومستقبل الوظائف.</p>',
    author: mockUsers[0],
    published_at: '2024-07-09T18:00:00Z',
    featured_image: 'https://picsum.photos/seed/post9/600/400',
    is_trending: false,
    tags: ['أخلاقيات', 'مجتمع', 'مستقبل'],
    views: 1200,
    comments_count: 30,
  },
  {
    id: 'post-10',
    title: 'Gemini مقابل GPT-4: مقارنة بين عمالقة نماذج اللغة',
    slug: 'gemini-vs-gpt4',
    content_html: '<p>مقارنة شاملة بين قدرات النموذجين في مجالات مثل فهم السياق، الإبداع، والقدرة على التحليل المنطقي.</p>',
    author: mockUsers[1],
    published_at: '2024-07-08T13:00:00Z',
    featured_image: 'https://picsum.photos/seed/post10/600/400',
    is_trending: true,
    tags: ['مقارنة', 'Gemini', 'GPT-4'],
    views: 3500,
    comments_count: 45,
  },
  {
    id: 'post-11',
    title: 'دليلك لإنشاء صور فوتوغرافية واقعية بالذكاء الاصطناعي',
    slug: 'photorealistic-ai-images',
    content_html: '<p>نصائح وأوامر متقدمة للحصول على صور لا يمكن تمييزها عن الصور الفوتوغرافية الحقيقية، مع التركيز على الإضاءة والتفاصيل الدقيقة.</p>',
    author: mockUsers[0],
    published_at: '2024-07-07T16:00:00Z',
    featured_image: 'https://picsum.photos/seed/post11/600/400',
    is_trending: false,
    tags: ['تصوير', 'واقعي', 'Midjourney'],
    views: 2200,
    comments_count: 19,
  },
  {
    id: 'post-12',
    title: 'من الصفر إلى الاحتراف: دليلك الشامل لـ Midjourney V6',
    slug: 'midjourney-v6-guide',
    content_html: '<p>دليل شامل يغطي كل شيء من الأوامر الأساسية إلى الميزات المتقدمة مثل --style raw و --stylize لمساعدتك على إتقان Midjourney V6.</p>',
    author: mockUsers[1],
    published_at: '2024-07-06T10:00:00Z',
    featured_image: 'https://picsum.photos/seed/post12/600/400',
    is_trending: true,
    tags: ['Midjourney', 'دليل', 'توليد الصور'],
    views: 2900,
    comments_count: 33,
  },
  {
    id: 'post-13',
    title: 'أتمتة المهام اليومية باستخدام AI: وفر وقتك وجهدك',
    slug: 'automate-daily-tasks-with-ai',
    content_html: '<p>استخدم أدوات الذكاء الاصطناعي لأتمتة المهام المتكررة مثل تلخيص رسائل البريد الإلكتروني، تنظيم الملاحظات، وجدولة الاجتماعات.</p>',
    author: mockUsers[0],
    published_at: '2024-07-05T09:00:00Z',
    featured_image: 'https://picsum.photos/seed/post13/600/400',
    is_trending: false,
    tags: ['إنتاجية', 'أتمتة', 'أدوات'],
    views: 1300,
    comments_count: 7,
  },
  {
    id: 'post-14',
    title: 'كيف تستخدم برمباتي لتحسين عملك؟ دراسة حالة',
    slug: 'prompaty-case-study',
    content_html: '<p>دراسة حالة توضح كيف استخدمت شركة تسويق منصة برمباتي لإنشاء محتوى عالي الجودة لعملائها، مما أدى إلى زيادة التفاعل بنسبة 40%.</p>',
    author: mockUsers[1],
    published_at: '2024-07-04T14:00:00Z',
    featured_image: 'https://picsum.photos/seed/post14/600/400',
    is_trending: false,
    tags: ['دراسة حالة', 'أعمال', 'برمباتي'],
    views: 950,
    comments_count: 5,
  },
  {
    id: 'post-15',
    title: 'مستقبل البحث: كيف يغير الذكاء الاصطناعي طريقة وصولنا للمعلومات؟',
    slug: 'future-of-ai-search',
    content_html: '<p>نظرة على محركات البحث المعززة بالذكاء الاصطناعي وكيف ستقدم إجابات مباشرة وتجارب بحث مخصصة بدلاً من مجرد روابط.</p>',
    author: mockUsers[0],
    published_at: '2024-07-03T11:00:00Z',
    featured_image: 'https://picsum.photos/seed/post15/600/400',
    is_trending: false,
    tags: ['مستقبل', 'بحث', 'تقنية'],
    views: 1150,
    comments_count: 14,
  },
  {
    id: 'post-16',
    title: 'تصميم الشعارات بالذكاء الاصطناعي: هل سيحل محل المصممين؟',
    slug: 'ai-logo-design',
    content_html: '<p>تحليل لقدرات أدوات تصميم الشعارات بالذكاء الاصطناعي، ومناقشة ما إذا كانت أداة مساعدة للمصممين أم بديلاً كاملاً لهم.</p>',
    author: mockUsers[1],
    published_at: '2024-07-02T16:00:00Z',
    featured_image: 'https://picsum.photos/seed/post16/600/400',
    is_trending: false,
    tags: ['تصميم', 'شعار', 'مستقبل الوظائف'],
    views: 1700,
    comments_count: 28,
  },
  {
    id: 'post-17',
    title: '5 أخطاء شائعة يجب تجنبها عند كتابة الأوامر',
    slug: 'common-prompting-mistakes',
    content_html: '<p>من الغموض الشديد إلى نقص السياق، استعرض أشهر الأخطاء التي يقع فيها المبتدئون وتعلم كيفية تجنبها للحصول على نتائج أفضل.</p>',
    author: mockUsers[0],
    published_at: '2024-07-01T10:00:00Z',
    featured_image: 'https://picsum.photos/seed/post17/600/400',
    is_trending: false,
    tags: ['نصائح', 'أساسيات', 'هندسة الأوامر'],
    views: 1950,
    comments_count: 16,
  },
  {
    id: 'post-18',
    title: 'إنشاء موسيقى بالذكاء الاصطناعي: أدوات للمبتدئين والمحترفين',
    slug: 'ai-music-generation',
    content_html: '<p>استعراض لأفضل منصات توليد الموسيقى بالذكاء الاصطناعي التي تتيح لك إنشاء مقطوعات موسيقية فريدة بدون أي خبرة موسيقية.</p>',
    author: mockUsers[1],
    published_at: '2024-06-30T13:00:00Z',
    featured_image: 'https://picsum.photos/seed/post18/600/400',
    is_trending: false,
    tags: ['موسيقى', 'إبداع', 'أدوات'],
    views: 1400,
    comments_count: 10,
  },
  {
    id: 'post-19',
    title: 'الذكاء الاصطناعي في التعليم: فرص وتحديات',
    slug: 'ai-in-education',
    content_html: '<p>كيف يمكن للذكاء الاصطناعي تخصيص تجربة التعلم لكل طالب، وما هي التحديات التي يجب مراعاتها لضمان استخدامه بفعالية وأمان؟</p>',
    author: mockUsers[0],
    published_at: '2024-06-29T09:00:00Z',
    featured_image: 'https://picsum.photos/seed/post19/600/400',
    is_trending: false,
    tags: ['تعليم', 'مستقبل', 'مجتمع'],
    views: 1050,
    comments_count: 8,
  },
  {
    id: 'post-20',
    title: 'كيفية بناء مساعد شخصي باستخدام واجهات برمجة التطبيقات (APIs) للذكاء الاصطناعي',
    slug: 'build-personal-ai-assistant',
    content_html: '<p>دليل خطوة بخطوة للمطورين حول كيفية استخدام واجهات برمجة التطبيقات مثل Gemini API لبناء مساعد ذكي مخصص.</p>',
    author: mockUsers[1],
    published_at: '2024-06-28T17:00:00Z',
    featured_image: 'https://picsum.photos/seed/post20/600/400',
    is_trending: false,
    tags: ['برمجة', 'API', 'دليل', 'Gemini'],
    views: 1850,
    comments_count: 24,
  },
  {
    id: 'post-21',
    title: 'التحقق من الحقائق في عصر الذكاء الاصطناعي: أدوات وتقنيات',
    slug: 'fact-checking-in-ai-era',
    content_html: '<p>مع انتشار المحتوى المولّد بالذكاء الاصطناعي، تزداد أهمية التحقق من صحة المعلومات. تعرف على أدوات وتقنيات تساعدك في ذلك.</p>',
    author: mockUsers[0],
    published_at: '2024-06-27T12:00:00Z',
    featured_image: 'https://picsum.photos/seed/post21/600/400',
    is_trending: false,
    tags: ['مجتمع', 'معلومات مضللة', 'أدوات'],
    views: 900,
    comments_count: 13,
  },
  {
    id: 'post-22',
    title: 'نصائح لإنشاء برومبات فيديو سينمائية باستخدام Veo',
    slug: 'tips-for-cinematic-video-prompts-veo',
    content_html: '<p>تعلم كيفية استخدام مصطلحات التصوير السينمائي مثل "dolly zoom" و "golden hour lighting" في أوامرك لإنشاء مقاطع فيديو احترافية.</p>',
    author: mockUsers[1],
    published_at: '2024-06-26T15:00:00Z',
    featured_image: 'https://picsum.photos/seed/post22/600/400',
    is_trending: true,
    tags: ['فيديو', 'Veo', 'نصائح', 'سينمائي'],
    views: 2600,
    comments_count: 29,
  },
];

// Function to add a new prompt to the mock data
export const addPrompt = (newPrompt: Prompt) => {
  mockPrompts.unshift(newPrompt); // Add to the beginning of the array
};

// Function to add a new post to the mock data
export const addPost = (newPost: Post) => {
  mockPosts.unshift(newPost);
};